### ISSUE TITLE
Code execution speed

### ISSUE THREAD

**Issue by blitheinsz** [FrDH/dotdotdot-js#157]
**If I have a text that contains 600 characters or more,      function:   this.truncate() will cost a lot of time**

hope you can to  optimize the code.    thanks

**Comment by anki247** [comment]
I my case the version 3.x got worse and really slow
version 2.0.1 needs 55ms
version 3.2.2 needs **12.607ms**
for the exact same text.... 😕 

Demo:
[Codepen V2](https://codepen.io/Anki247/pen/wXZRwZ)
[Codepen V3](https://codepen.io/Anki247/pen/RJOPpa)

Additionally the v3 ignores the height of the wrapper element, if select multiple elements (see the second section in codepen v3)
Both of them ignores the padding if you have list items.

**Comment by anki247** [comment]
@FrDH Do you need more info?

**Comment by FrDH** [comment]
Could you please try with the latest version? Although the logic itself didn't change, the plugin no longer needs jQuery and execution should be faster in vanilla js.

**Comment by anki247** [comment]
https://codepen.io/Anki247/pen/mgXrLe?editors=0010
nope 13,484ms and I see nothing...

**Comment by FrDH** [comment]
I got about 300 or 400 ms and an empty DIV. I really don't understand why the script would fail, the demo file in the download pack seems to work as intended.

**Comment by alex-bukach** [comment]
I have a performance issue too with versions 3 and 4. I confirm it's gone with 2.0.1 however that version does not have necessary features for me.

**Comment by anki247** [comment]
Why is this issue closed? I have no idea which setup you (@FrDH ) have but for me it takes over 

- 13sec!!! (i7 16GB)
-  190sec on Samsung S9

AND obviously it completely fails to truncate the text in v4 (see last codepen link) 
The biggest problem is that this plugin blocks the main thread meanwhile which means all function calls that would invoke after dotdotdot are delayed.

**Comment by anki247** [comment]
Regarding performance issue... I found a really nice article about how react internally works, which can be quit helpful :-) 
https://pomb.us/build-your-own-react/
The interesting part is  "**Step III: Concurrent Mode**". How to run big task without blocking the main thread.
