### ISSUE TITLE
Not working in IE 11.2007.14393.0

### ISSUE THREAD

**Issue by Knight017** [FrDH/dotdotdot-js#158]
Hi, first of all, nice plugin.

But it seems it is not working with **IE 11.2007.14393.0**  but however, it is working in other versions
![ie_11_dotdotdot](https://user-images.githubusercontent.com/18218393/45689912-cfb1c500-bb72-11e8-9a5f-1f1cd7bacbfe.png)
 of **IE 11.x.x.x** . Strange but i'm not sure about this. As your  [documentation link](http://dotdotdot.frebsite.nl/) 's example is not working properly in **IE 11.2007.14393.0**.

Thank you.

**Comment by FrDH** [comment]
Thank you for reporting this, I have no idea why only 11.2007.14393.0 wouldn't work. Are there any errors in the console?

**Comment by Yakoot** [comment]
SCRIPT438: Object doesn't support property or method 'append'

**Comment by FrDH** [comment]
I think you'll need a polyfill for IE11:
https://polyfill.io/v3/url-builder

I'll add this information to the browser support section on the website.
