### ISSUE TITLE
How to use with ES6 modules?

### ISSUE THREAD

**Issue by Safe-Mode** [FrDH/dotdotdot-js#160]
I have installed this plugin throught npm and try to include it by `import 'jquery.dotdotdot'` since we haven't got any exports from it. But I get this error `Uncaught TypeError: e(...).dotdotdot is not a function`. Is there any method to include it with es6 modules? I use rollup with cjs plugin.

**Comment by FrDH** [comment]
Good question, the plugin uses [gulp-umd](https://www.npmjs.com/package/gulp-umd) for implementing the Universal Module Definition, not sure if that supports ES6 modules at all.

**Comment by Safe-Mode** [comment]
> Good question, the plugin uses [gulp-umd](https://www.npmjs.com/package/gulp-umd) for implementing the Universal Module Definition, not sure if that supports ES6 modules at all.

Everything was fine when I used browserify to bundle js, so I had think if I'd be using commonjs plugin for rollup I'd be able to import it by es6 syntax. Probably I should use anything like umdjs plugin or I don't know what?

**Comment by FrDH** [comment]
I think for now you'll need to manually remove the UMD pattern and replace it with an ES6 export:

Remove this:
````js
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory();
  } else {
    root.Dotdotdot = factory();
  }
}(this, function() {
````
and the last two lines:
````js
return Dotdotdot;
}));
````

Add prepend `var Dotdotdot` with the export:
````js
export default var Dotdotdo
````

I'll see if I can compile a seporate ES6 file in the next release.

**Comment by Safe-Mode** [comment]
Would be nice)

**Comment by FrDH** [comment]
Version 4.0.3 includes separated es6 and umd files.
You should be able to use the module like this:
````js
import Dotdotdot from "./path/to/dotdotdot.es6.js";
new Dotdotdot( element, {
   // options
});
````

**Comment by schmidex** [comment]
maybe set `"main": "dist/dotdotdot.es6.js"` in `package.json` so that we could simply do
`import Dotdotdot from "dotdotdot-js";`
Or would this break other things... sorry iam new to this.

**Comment by tibineagu** [comment]
@FrDH I opened PR #165 that resolves this.
