### ISSUE TITLE
Chrome not updating content

### ISSUE THREAD

**Issue by JimDutton** [FrDH/dotdotdot-js#161]
I use appendExternalFile to add the content of a text file containing the material to be truncated with dotdotdot. It works without a hitch most of the time. But, in Chrome, if I make a change to the external file, hit Ctrl-F5 to force a reload, dotdotdot no longer works: it seems to be "confused" and either the "more" link does nothing, or the link continues to say "more" when "less" should be appearing. The only way to fix this is to close the Chrome tab and open the site again. In Edge or Firefox, this does not occur; dotdotdot continues to work regardless of changes to the text file. Any ideas on how to fix this would be appreciated.

**Comment by FrDH** [comment]
Im not sure what "appendExternalFile" is, but is it asynchrone? If so, you should trigger the `truncate` API method. Setting the `watch` option to `true` should also work I guess.
