### ISSUE TITLE
ie11 and @babel/bolyfill

### ISSUE THREAD

**Issue by Yakoot** [FrDH/dotdotdot-js#163]
Hello! I've create a test vue.js component with basic example from dotdotdot site.
https://github.com/Yakoot/testie11-dotdotdot
I'm trying to make it work in ie11 with @babel/polyfill, can anyone help?

[Vue warn]: Error in mounted hook: "TypeError: Object doesn't support property or method 'append'"

**Comment by helenasw** [comment]
@babel/polyfill doesn't include any Dom polyfills, so you'll need to use another polyfilling library. I'm currently trying to get it to work with [dom4](https://www.npmjs.com/package/dom4), but I'm having a bit of trouble.
