### ISSUE TITLE
Question: Conflict with Foundation 5 tooltip with V3

### ISSUE THREAD

**Issue by erikjohnsen6d** [FrDH/dotdotdot-js#164]
Hello licensed owner here, in v3.2.2 there are these lines:

```
var c = document.createComment( '' );
$e.replaceWith( c );
_elms.push( this );
_coms.push( c );
```

These lines for some reason conflict with Foundation 5's tooltip, regardless of initialization order. If the lines above are removed, everything seems to work. I wanted to confirm the reason for the code above, it's implications on functionality, and/or if it is required for functionality, or if it's just a comment generator/placeholder.

```
Uncaught TypeError: a.getAttribute is not a function
    at Function.b.attr (VM3012 jquery.js:24)
    at Array.<anonymous> (VM3012 jquery.js:24)
    at VM3012 jquery.js:24
    at g (VM3012 jquery.js:24)
    at b.select (VM3012 jquery.js:24)
    at Function.b [as find] (VM3012 jquery.js:24)
    at HTMLDocument.handlers (VM3012 jquery.js:25)
    at HTMLDocument.dispatch (VM3012 jquery.js:25)
    at HTMLDocument.q.handle (VM3012 jquery.js:24)
    at Comment.<anonymous> (VM3012 jquery.js:25)
```

https://codepen.io/anon/pen/oOxZRW

Oddly, it does not happen when the css is unapplied. 

Thank you.

**Comment by FrDH** [comment]
The HTML nodes are temporarely replaced with a comment node, only the nodes that fit in the available space are placed back in to the DOM. So removed those lines will probably break the plugin.
I'll have a look at the codepen and see if I can find why the error occurs.

**Comment by FrDH** [comment]
Could you update the dotdotdot library to the latest version?

**Comment by erikjohnsen6d** [comment]
Thank you for your response, I'd prefer not to upgrade to the new version, but the issue appears to be there even with the new version: https://codepen.io/anon/pen/OGNmxq

I've also tried updating to last version of foundation 5, and last version of dotdotdot 3 unsuccessfully (not in the pen above) They just don't play nice :( 

I know this isn't a dotdotdot specific problem. Do you think I could remove the links in the original post without issue, as it appears to be working without those lines?

**Comment by erikjohnsen6d** [comment]
Noodle-scratcher now though.... downgrading to 1.7.2 works: https://codepen.io/anon/pen/oOxWVM

**Comment by erikjohnsen6d** [comment]
Hello, any further comments here?

**Comment by erikjohnsen6d** [comment]
The solution we're going to try is this:
(function() {
  var fn = $.fn.dotdotdot;
  $.fn.dotdotdot = function() {
    $(this).on('DOMNodeRemoved', function(e){
      e.stopPropagation();
    });
    fn.apply(this, arguments);
  }
})();
```
Thoughts?
