### ISSUE TITLE
UglifyJS cannot work with ES6 (ES2015) code in module

### ISSUE THREAD

**Issue by tibineagu** [FrDH/dotdotdot-js#166]
This is also related to #160 

Users of `DotDotDot` are [now](https://github.com/FrDH/dotdotdot-js/commit/11fe4c763fe3d0201fa7e97fd8c266b07f49f7aa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R5) able to use the `import` syntax.
```js
import Dotdotdot from 'dotdotdot-js';
```

However, when using a bundler such as `webpack` and generating production-ready code using `UglifyJS`, the uglifier throws an error similar to the following:
```
ERROR in {FILE_NAME} from UglifyJs
Unexpected token: name (Dotdotdot) [{FILE_NAME}:{LINE_NUMBERS}]
```

I've done a bit of research on this and can confirm that [indeed, Uglify cannot parse ES6](https://github.com/webpack/webpack/issues/2972#issuecomment-261705632).

I've done some follow-up research related to my initial PR #165 it looks like the files indicated in the `pkg.module` should **ONLY** contain `export` statements (which are ES6/ES2015-specific), but the rest of the code should _only use syntax features that the target environments support_.
- [See this indication in the `rollup` wiki](https://github.com/rollup/rollup/wiki/pkg.module)
- [See this indication in the `webpack` guide](https://webpack.js.org/guides/author-libraries/#final-steps)

**Comment by tibineagu** [comment]
@FrDH opened #167 which should solve this for good. Would be very grateful if you could have a look and merge, as we are planning to use your library in production.

**Comment by FrDH** [comment]
Just out of curiosity, could you not switch from uglify to terser?

**Comment by tibineagu** [comment]
> Just out of curiosity, could you not switch from uglify to terser?

@FrDH to be honest I had no idea about terser until now. There seems to be some discussion around whether or not to use terser or uglify with webpack, but currently both are supported ([Terser](https://webpack.js.org/plugins/terser-webpack-plugin/) / [Uglify](https://webpack.js.org/plugins/uglifyjs-webpack-plugin)).

However, the underlying issue is that even if developers were to use an uglifier that supports ES6, if the original code is written in ES6, the bundled code would still be incompatible with some target browsers (the zombie IE11). I believe that's why both `rollup` and `webpack` suggest that `pkg.module` references a file compatible with whatever environments the library author wants to support.

In the end, as the author of the package, it is your decision if you want your library to work on these older browsers, but if you do, then I believe your decision to merge my PR was the right one (and we're very grateful for that!).
