### ISSUE TITLE
dist/dotdotdot.esm.js not found

### ISSUE THREAD

**Issue by tibineagu** [FrDH/dotdotdot-js#168]
@FrDH after merging #167 the `dist/` files were not rebuilt.

Therefore the `dist/dotdotdot.esm.js` file referenced in [`module`](https://github.com/FrDH/dotdotdot-js/blob/b53c98d461658157bbdebf822019d803c05c2513/package.json#L5) was not been created and added to the repo in b53c98d461658157bbdebf822019d803c05c2513

Could you run the build task and add the file to the repo?

I'm sorry I didn't add it myself in the PR, wasn't sure what your policy is on these things, usually the authors prefer to do the version bump and rebuild after the contributor pulls are merged.

**Comment by FrDH** [comment]
should be fixed :)

**Comment by tibineagu** [comment]
Thanks @FrDH - seems to be all good now!
