### ISSUE TITLE
Support for pre-style

### ISSUE THREAD

**Issue by pbrach** [FrDH/dotdotdot-js#169]
Wouldn't it be good to extend dotdotdot to support divs with syle: `white-space: pre;` ?

Sometimes you come across a requirement like "The user wants to enter and see tabs". Using dotdotdot in those scenarios won't work. I had once a problem because of this line (127 in dotdotdot.ts):

```
    if (computedStyle['white-space'] === 'nowrap') {
            this.container.style['white-space'] = 'normal';
}
```

I basically could solve the issue by also **adding**:
```
    if (computedStyle['white-space'] === 'pre') {
            this.container.style['white-space'] = 'pre-wrap';
}
```

...Still: I have to admit that I did not yet read and understand all of the lib and if this is generally a good idea. 

But I would be glad if this is a good extension for pre-styled elements also from your perspective?!

**Comment by FrDH** [comment]
Hi,
I don't see any problem with this addition. The idea of the white-space is to ensure the text wraps around multiple lines of code. I'll implement this in the next release.

**Comment by FrDH** [comment]
added in v4.0.9
