### ISSUE TITLE
Specific case where dotdotdot.js does not truncate

### ISSUE THREAD

**Issue by raoulaudouin** [FrDH/dotdotdot-js#171]
I found a specific case where dotdotdot.js does not truncate:

```
<div class="truncate">
	<article>Lorem ipsum dolor sit amet…</article>
	<!-- comment -->
</div>
```

I have no idea why, but removing the comment or changing the `<article>` tag by a `<div>` tag fixes the issue.

I suspect that the issue comes from a lack of support of some HTML5 tags, because replacing the `<article>` tag by a `<section>` tag does not fix the issue.

Here's a [jsfiddle](https://jsfiddle.net/Raoulito/j3etd4wf/) of the issue.

**Comment by FrDH** [comment]
Hi, thanks for reporting the issue.
dotdotdot uses comments to hide content that doesn't fit, my guess is there's a conflect if there already is a comment node.
I'll investigate later on.

**Comment by FrDH** [comment]
I think I found and fixed the problem. Give 4.0.10 a try.

**Comment by raoulaudouin** [comment]
Great job thanks!
