### ISSUE TITLE
Truncate all text when height is fixed

### ISSUE THREAD

**Issue by Safe-Mode** [FrDH/dotdotdot-js#172]
Truncate the whole text when I set not max-height css property but just height then text block comes empty (without text). Has anyone got this trouble and how to fix?

**Comment by FrDH** [comment]
I'll have to investigate but I think that should simply work. Is there an online example I could have a look at?

**Comment by Safe-Mode** [comment]
> 
> 
> I'll have to investigate but I think that should simply work. Is there an online example I could have a look at?

https://codepen.io/Safe_Mode/pen/QWLPZWz

Seems like it's just removing inner element wrapped by truncated node.

**Comment by FrDH** [comment]
I think you can't use `em` values for the `height`. I don't know why it appears to work with `max-height` though.
