### ISSUE TITLE
I try to put the text on one line, without punctuation, spaces, and carriage returns, and then display only the ellipsis.

### ISSUE THREAD

**Issue by TriteLove** [FrDH/dotdotdot-js#174]
<!DOCTYPE html>
    <html lang="en">

    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Document</title>
      <style>
        .dotdotdot {
          width: 100px;
          height: 300px;
          margin: 30px auto;
        }

        p {
          text-align: justify;
        }
      </style>
    </head>
    <body>
        <div class="dotdotdot">
          <p>
            The dotdotdot javascript plugin targets modern browsers that support ES5 meaning Internet Explorer 10 and earlier are not supported For Internet Explorer 11 you''ll need some polyfills If you need support for Internet Explorer 9 or 10 use the legacy (jQuery) version: version 3.2.3.
          </p>
        </div>
        <div class="dotdotdot">
          <p>
            截至2008年底国务院国有资产监督管理委员会履行出资人职责的企业（以下简称中央企业）共计141家根据中央企业编制上报并经注册会计师审计的财务决算报告将2008年度中央企业基本财务情况公告如下
          </p>
        </div>
      </body>
    <script src="https://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <script src="./dist/dotdotdot.js"></script>
    <script>
      $(document).ready(function(){
        $('.dotdotdot').dotdotdot({

        })
      })
    </script>

    </html>

**Comment by FrDH** [comment]
Try setting the `truncate` option to `"letter"`
````js
$(".dotdotdot").dotdotdot({
    truncate: "letter"
});
````

If that doesn't help, please provide an online example.
