### ISSUE TITLE
IE11 replaceWith problem

### ISSUE THREAD

**Issue by eye1985** [FrDH/dotdotdot-js#175]
Hi, 
I still get this error even after adding replaceWith polyfill from MDN.
(https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith)

Error in IE:
Object doesn't support property or method 'replaceWith'

**Comment by FrDH** [comment]
What version of IE?

**Comment by eye1985** [comment]
I tested this again today, cannot seem to reproduce it now. Guess its fixed.

Thanks.
