### ISSUE TITLE
Box-sizing content-box not working

### ISSUE THREAD

**Issue by mfrieling** [FrDH/dotdotdot-js#176]
### Problem/Motivation
I want to truncate text inside a `div` element which is responsive (using Bootstrap 4, which means it neither has a fixed height nor fixed width) and has a calculated `max-height` applied via a CSS class. The actual value of the max-height depends on the current active breakpoint (md, lg).

As it didn't work as expected I looked into the source code of _DotDotDot_ and found that it handles `max-height` calculation for box-sizing values `border-box` and `padding-box` (which actually is not a valid value according to [w3schools.com](https://www.w3schools.com/cssref/css3_pr_box-sizing.asp)), but not it's default value `content-box` (only the content height without paddings and borders).

### Proposed solution
- Remove the `padding-box` switch from the height calculation as this is not a defined value by the [CSS specification](https://www.w3schools.com/cssref/css3_pr_box-sizing.asp).
- Add a switch `content-box` which is the default value of `box-sizing`.

**Comment by FrDH** [comment]
Thank you for reporting the issue, please give version 4.0.11 a try.
