### ISSUE TITLE
Add access to the original value to the callback function

### ISSUE THREAD

**Issue by mfrieling** [FrDH/dotdotdot-js#177]
It would be nice to have access to the original "value" inside the callback function to apply further customizations like adding the full un-truncated text as `title` attribute or even as styled HTML tooltip (using libraries for this like [Popper.js](https://popper.js.org/)).

I'm not quite sure how to extend the callback signature. Here are three variants which all have their pros and cons, which should be discussed here before implementing it:

1. Simply add a second parameter `fullText` (which doesn't contain HTML but the `this.container.innerText` value)
2. Add the `DotDotDot` instance as second parameter, which might be too much and could cause loops
3. Add the `originalStyle` and `originalContent` properties of the `DotDotDot` instance as second and third parameter

**Comment by FrDH** [comment]
Could not you store the original value before initiating the plugin? 
````js
var orig = wrapper.innerText;
new Dotdotdot(wrapper);
````

Or you could access the `originalContent` var for the instance, it is a slimmed down Nodelist:
````js
var dot = new Dotdotdot(wrapper);
var orig = dot.originalContent;
````

Hope this helps.

**Comment by mfrieling** [comment]
Unfortunately both your suggestions don't help. I tried the first one, but then I only have the full text only available directly after the first possible truncation when creating the DotDotDot instance, but not on subsequent truncations (or un-truncations) triggered by the watcher.

The second doesn't work because the context of the callback function is the wrapper HTMLElement instance and not the DotDotDot instance. A new instance should not be created for the wrapper because an already wrapped and possibly truncated element could be truncated again, especially if you cannot guarantee to pass in the exact same options as for the original call.

Of course you could change the context by passing in `this` instead of `this.container` as context object to the function. But I didn't suggest that as it would introduce a breaking change into the API affecting all users depending on the context object inside their callback function. Adding that object as an additional optional parameter would have no impact on existing callback implementations instead.

**Comment by FrDH** [comment]
Could you share some code please?
