### ISSUE TITLE
Works with some heights, doesn't work with some others...

### ISSUE THREAD

**Issue by aderchox** [FrDH/dotdotdot-js#179]
Here's a pen I have created for my issue: [pen](https://codepen.io/aderchox/pen/xxGyBwV)
Please change the max-height in the CSS from 18em to 16em and see what happens. It won't show ellipsis anymore and the paragraph goes out of the white box and enters over the purple box.
Also I have to mention two things: 1_This is only the case when I use the javascript plugin, I don't have the same issue when I use the jQuery plugin. 2_Sometimes when I refresh the page multiple times, it truncates the bottom paragraph completely which is an accepted result, but it can only be observed inconsistently(by chance).
Thanks in advance.

**Comment by FrDH** [comment]
I guess this makes sense, with a 16em max-height, the <p> doesn't fit (even if empty) due to its padding and margin, so it is removed. Next thing that does fit (the image) can not get an ellipsis.
