### ISSUE TITLE
Update documentation for 'watch' option

### ISSUE THREAD

**Issue by nicholaschiang** [FrDH/dotdotdot-js#183]
In your code, it's quite clear that the `watch` option should be either `window`, `resize`, or `undefined`:

```typescript
interface dddOptions {
	/** Whether and when to update the ellipsis: null, 'window' (default) or 'resize' */
	watch 		?: string,
}
```

And yet your website indicates that `watch` can/should be a boolean (when you want to watch the width and height of the container):

> Whether to update the ellipsis:
> 1. `true`: Monitors the wrapper width and height;
> 2. `"window"`: Monitors the window width and height.

While it does still works when you pass `true` (due to the weird way you wrote your logic), you **should update the documentation on [the website](https://dotdotdot.frebsite.nl/) to match what is defined in your Typescript source files.**

**Comment by FrDH** [comment]
> due to the weird way you wrote your logic

I agree :)  It's either "window" or anything other that isn't falsy :/
I'll update the script so it matches the docs.
