### ISSUE TITLE
Callback not passing wrapper reference

### ISSUE THREAD

**Issue by ckpicker** [FrDH/dotdotdot-js#184]
Hello!  I'm experimenting with the `callback` option, and I can't seem to get a reference to the wrapper in my function.  Here's how I'm calling it:

```
new Dotdotdot(element, {
    callback: (isTruncated) => {
      console.log(this);
    },
    height: 50,
    keep: '.text-toggle',
    tolerance: 10,
  });
```

All I get is `undefined` when I try to log `this` to the console, however `isTruncated` is correctly returning a boolean value.  Any ideas?  Thanks!

**Comment by FrDH** [comment]
Where did you read `this` should point to the wrapper?
You can store the wrapper in a variable if you need it later on:
````js
const wrapper = document.querySelector(".wrapper");
new Dotdotdot(wrapper, {
   callback: isTruncated => {
      console.log(wrapper)
   }
});
````
