### ISSUE TITLE
Do I need to do any additional actions after buying a license

### ISSUE THREAD

**Issue by EduardTrayan** [FrDH/dotdotdot-js#186]
Dear owner,

Should I do any additional actions after buying a license?

I'm going to use this plugin for commercial purposes and I've already bought a license.

Thanks in advance

**Comment by FrDH** [comment]
Hello Eduard,

No you do not need to do any additional actions. Please just make sure the plugin does what you expect it to do in your project.

Regards, Fred
________________________________
Van: Eduard Trayan <notifications@github.com>
Verzonden: donderdag 22 oktober 2020 13:11
Aan: FrDH/dotdotdot-js <dotdotdot-js@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [FrDH/dotdotdot-js] Do I need to do any additional actions after buying a license (#186)


Dear owner,

Should I do any additional actions after buying a license?

I'm going to use this plugin for commercial purposes and I've already bought a license.

Thanks in advance
